@startuml

class Livre {
       titre: String
       datePublication: Date
       genre : String[1...*]
       motsCles: String[1...*]
}

class Abonne {

}

class Emprunte {
      - dateRenduPrevue: Date
      - dateRenduReelle: Date
}


Livre "0..*" --- "1" Abonne


(Livre, Abonne) ... Emprunte

@enduml
