@startuml

class Emprunte {
      - dateRenduPrevue: Date
      - dateRenduReelle: Date
}

class Livre {
       titre: String
       datePublication: Date
       genre : String[1...*]
       motsCles: String[1...*]
}

class Abonne {

}

Abonne "1" --- "0..*" Livre

(Livre, Abonne) ... Emprunte

@enduml
