site:
  title: XMS2IE300 - Domain Analysis
  url: https://gl.univ-nantes.io/analysis/labs
  start_page: labs::index.adoc
asciidoc:
  attributes:
    author: Gerson Sunyé
    email: gerson.sunye@univ-nantes.fr
    source-highlighter: highlight.js
    highlightjs-theme: googlecode
    kroki-fetch-diagram: true
    kroki-server-url: http://kroki:8000
    kroki-plantuml-include: ./resources/defaults/plantuml/puml-theme-sober.puml
    kroki-plantuml-include-paths: "./resources/defaults/plantuml/"
    lang: fr
    sectnums: true
    math: true
    stem: latexmath
    icons: font
    title-separator: "::"
    xrefstyle: short
    figure-caption: Figure
    important-caption: Important
    last-update-label: Dernière mise à jour
    appendix-caption: Annexe
    appendix-refsig: Annexe
    caution-caption: Attention
    example-caption: Exemple
    note-caption: Note
    table-caption: Tableau
    tip-caption: Astuce
    toc-title: Table des matières
    untitled-label: Sans titre
    version-label: Version
    warning-caption: Avertissement
    pdfscale_xl: 70%
    pdfscale_l: 60%
    pdfscale_m: 50%
    pdfscale_s: 40%
    pdfscale_xs: 30%

  extensions:
    - asciidoctor-kroki

content:
  sources:
    - url: .
      start_path: ./exercices/
      branches: HEAD

ui:
  bundle:
    url: https://gitlab.univ-nantes.fr/gl/antora-custom-nu-theme/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

antora:
  extensions:
    - require: '@antora/lunr-extension'
      languages: [fr]

urls:
  html_extension_style: indexify