@startuml
class Livre {
       titre: String
       isbn: String
       datePublication: Date
       motsCles: String[1...*]
}

enum Genre {

}

class Auteur {

}

class Editeur {

}

Class Commande {

}

Class Disponible {

}

Class Reserve {

}

enum Section {
      adulte
      adolescent
      enfant
}

enum EtatEmprunt {
      actif
      passe
}

Class Emprunte {
      - dateRenduPrevue: Date
      - dateRenduReelle: Date
}

class CarteMembre {
   - nom : String
   - prenom : String
   - adresse : String
   - identifiant : Integer[1...10]
}

class Abonne {

}

class CommiteLecteur {

}


Livre "0..2" --- "1" Emprunte
Livre "1" --- "*" Auteur
Livre "1" --- "*" Editeur
Livre "1" --- "1" Section
Livre "1..*" --- "1..*" Genre


Emprunte "1" --- "1" EtatEmprunt
CommiteLecteur "1" --- "1..4" Emprunte
Abonne "1" --- "1..2" Emprunte
Abonne "1" --- "1" CarteMembre


@enduml

