@startuml
class Livre {
      - titre: String
      - auteurs: String[1...n]
      - isbn: String
      - editeurs: String[1...n]
      - datePublication: Date
      - genres: String[1...n]
      - motsCles: String[1...n]
      - etat: EtatLivre
}

enum EtatLivre {
      commande
      disponible
      emprunte
      reserve
}

enum Section {
      adulte
      adolescent
      enfant
}

enum Emprunt {
      actif
      passe
}

class CarteMembre {
   - nom : String
   - prenom : String
   - adresse : String
   - identifiant : int[1...10]
}

class Abonne {
    - carte : CarteMembre
}


class Bibliotheque {
    - section : Section
    - emprunts : Emprunt
    - dateRenduPrevue: Date
    - dateRenduReelle: Date

    + ajoutLivre() : boolean
    + enleverLivre() : boolean
}


EtatLivre "1" -- "0" Livre

Abonne "[0..n]" -- "[0..n]" Livre
(Livre,Abonne) . Emprunt

Abonne "1" -- "1" CarteMembre
Bibliotheque "1" -- "1" Section

@enduml

