== Commençons par définir les attributs et les concepts qui y sont associés.

=== Livre :
** Titre
** Date de publication
** Genre(s)
** MotsClés

=== ISBN :

=== Seection :
** adulte
** adolescent
** enfant

=== Emprunt :
** DateRenduPrevue
** DateRenduReelle

=== CarteMembre :
** nom
** prenom
** adresse
** identifiant

=== EtatEmprunt
** actif
** passe


=== CommiteLecteur :

=== Personne :
** nom
** prenom
** adresse

=== Bibliothécaire :
** ajouter()
** enlever()


=== Abonne :

=== Reserve :

=== Commande :

=== Auteur :

=== Editeur :

=== Disponible :


 Dessinez un diagramme de classes représentant la bibliothèque :

[plantuml]
....
@startuml
class Livre {
titre: String
datePublication: Date
genre : String[1...*]
motsCles: String[1...*]
}

class Abonne {

}

class Emprunte {
dateRenduPrevue: Date
dateRenduReelle: Date
}

class CarteMembre {
nom : String
prenom : String
adresse : String
identifiant : Integer[1...10]
}

class Isbn <<(D,#FF7700) DataType>> {
}

enum Section {
adulte
adolescent
enfant
}

Class Reserve {

}

Class Commande {

}

enum EtatEmprunt {
actif
passe
}


class CommiteLecteur {

}

class Personne {
nom : String
prenom : String
adresse : String
}

class Bibliothécaire {

 ajouter()
 enlever()
}


class Auteur {

}

class Editeur {

}



Class Disponible {

}

Livre "0..2" --- "1" Emprunte
Livre "1" --- "*" Auteur
Livre "1" --- "*" Editeur
Livre "1" --- "1" Section
Livre "1" --- "1" Isbn
Livre  ---  Disponible

Livre "0..*" --- "1" Abonne
(Livre, Abonne) .. Commande
(Livre, Abonne) .. Reserve


Personne  ---  Abonne
Personne  ---  Bibliothécaire

Emprunte "1" --- "1" EtatEmprunt
CommiteLecteur "1" --- "1..4" Emprunte
Abonne "1" --- "1..2" Emprunte
Abonne "1" --- "1" CarteMembre

Bibliothécaire  ---  Emprunte

@enduml
....


==  Diagramme de classes :

Le diagramme de classes permet de connaître :

** Tous les livres empruntés par un abonné.

[plantuml]
....
@startuml

class Emprunte {
      - dateRenduPrevue: Date
      - dateRenduReelle: Date
}

class Livre {
       titre: String
       datePublication: Date
       genre : String[1...*]
       motsCles: String[1...*]
}

class Abonne {

}

Livre "0..*" --- "1" Abonne

(Livre, Abonne) ... Emprunte

@enduml
....

** Tous les abonnés qui ont emprunté un livre.

[plantuml]
....
@startuml

class Emprunte {
      - dateRenduPrevue: Date
      - dateRenduReelle: Date
}

class Livre {
       titre: String
       datePublication: Date
       genre : String[1...*]
       motsCles: String[1...*]
}

class Abonne {

}

Abonne "1" --- "0..*" Livre

(Livre, Abonne) ... Emprunte

@enduml
....

** Toutes les adresses d'un abonné.

[plantuml]
....
@startuml

class Personne {
     nom : String
     prenom : String
     adresse : String
}

class Abonne {

}

Personne  ---  Abonne

@enduml
....


== Machine d'états pour la classe "Livre" :

==== États possibles :

Ces diagrammes représentent les différents états d'un livre et les transitions entre ces états en fonction des actions effectuées sur le livre.

** Commandé

[plantuml]
....

@startuml

state Commandé {
  [*] --> Disponible : réceptionner
}

@enduml
....

** Disponible

[plantuml]
....

@startuml

[*] --> Disponible

state Disponible {
  [*] --> Empruntable
  Empruntable --> Emprunté : emprunter
  Empruntable --> Réservé : réserver
  Empruntable --> Commandé : commander
  Empruntable --> Indisponible : rendre indisponible
}

@enduml
....

** Emprunté

[plantuml]
....

@startuml

state Emprunté {
  [*] --> Retour
  Retour --> Empruntable : retourner
}

@enduml
....

** Réservé

[plantuml]
....

@startuml

state Réservé {
  [*] --> Empruntable : annuler réservation
}

@enduml
....

== Invariants du diagramme :

** Invariant 1:  Un livre doit avoir au moins un auteur.

.Contraintes sur Livre
[source, ocl]
----
context Livre
inv UnLivreDoitAvoirUnAuteur:
  self.auteur->size() >= 1
----

** Invariant 2: Un livre peut avoir un ISBN seulement s'il a été publié après 1960.

.Contraintes sur Livre
[source, ocl]
----
context Livre
inv LivrePublieApres1960AUnISBN:
  self.datePublication > Date('1960-01-01') implies self.ISBN <> null
----

** Invariant 3: Un livre doit appartenir à une section

.Contraintes sur Livre
[source, ocl]
----
context Livre
inv UnLivreDoitAppartenirAUneSection:
  self.section <> null
----

** Invariant 4: Un abonné ne peut pas emprunter plus de deux livres à la fois.

.Contraintes sur Abonne
[source, ocl]
----
context Abonne
inv AbonneNePeutPasEmprunterPlusDeDeuxLivres:
  self.emprunts->size() <= 2
----

== Cas d'utilisation de la bibliothèque :
** Emprunter un livre : Un abonné emprunte un livre de la bibliothèque.
** Rendre un livre : Un abonné retourne un livre emprunté à la bibliothèque.
** Réserver un livre : Un abonné réserve un livre qui n'est pas disponible immédiatement.
** Commander un livre : Un bibliothécaire ou un abonné commande un livre qui n'est pas disponible dans la bibliothèque.
** Ajouter un livre : Un bibliothécaire ajoute un nouveau livre au fonds de la bibliothèque.
** Enlever un livre : Un bibliothécaire retire un livre du fonds de la bibliothèque.

[plantuml]
....

@startuml

actor "Abonné" as Abonne
actor "Bibliothécaire" as Bibliothecaire
actor "Comité de lecture" as ComiteLecture

Abonne --> (Emprunter)
Abonne --> (Rendre)
Abonne --> (Réserver)
Abonne --> (Commander)

Bibliothecaire --> (Ajouter)
Bibliothecaire --> (Enlever)

ComiteLecture --> (Emprunter)
ComiteLecture --> (ChangerSection)

@enduml
....

=== Cas d'utilisation : Emprunter un livre
** Pré-conditions :
Le livre doit être disponible.
L'abonné ne doit pas avoir atteint la limite d'emprunts.

** Post-conditions :
Le livre est marqué comme emprunté.
Les informations sur l'emprunt sont enregistrées dans le système.
Diagramme d'objets - Avant l'emprunt :


[plantuml]
....

@startuml

object Abonne {
    nom = "Jean"
    prenom = "Dupont"
    adresse = "123 rue de la Bibliothèque"
    cartemembre = "1234567890"
}

object Livre {
    titre = "Le Petit Prince"
    disponible = true
}


@enduml
....


=== Diagramme d'objets - Après l'emprunt :

[plantuml]
....

@startuml

object Abonne {
    nom = "Jean"
    prenom = "Dupont"
    adresse = "123 rue de la Bibliothèque"
    cartemembre = "1234567890"
}

object Livre {
    titre = "Le Petit Prince"
    disponible = false
}

@enduml
....


=== Cas d'utilisation : Rendre un livre
** Pré-conditions :
Le livre doit être emprunté par l'abonné.
La date de retour ne doit pas être dépassée.

** Post-conditions :
Le livre est marqué comme disponible.
Les informations sur le retour sont enregistrées dans le système.

=== Diagramme d'objets - Avant le retour :

[plantuml]
....

@startuml

object Abonne {
    nom = "Jean"
    prenom = "Dupont"
    adresse = "123 rue de la Bibliothèque"
    cartemembre = "1234567890"
}

object Livre {
    titre = "Le Petit Prince"
    disponible = false
}

@enduml
....


=== Diagramme d'objets - Après le retour :

[plantuml]
....

@startuml

object Abonné {
    nom = "Jean"
    prenom = "Dupont"
    adresse = "123 rue de la Bibliothèque"
    cartemembre = "1234567890"
}

object Livre {
    titre = "Le Petit Prince"
    disponible = true
}

@enduml
....

== Cas d'utilisation : Emprunter un livre

Diagramme de séquence

[plantuml]
....

@startuml

actor Abonne
participant Bibliothèque
participant Livre

Abonne -> Bibliothèque: emprunterLivre(livre: Livre)
Bibliothèque -> Livre: vérifierDisponibilité(livre)
alt livre disponible
    Livre -> Bibliothèque: marquerEmprunt(livre)
    Bibliothèque --> Abonné: confirmerEmprunt()
else livre non disponible
    Bibliothèque --> Abonne: signalerIndisponibilité(livre)
end

@enduml
....

== Cas d'utilisation : Rendre un livre

Diagramme de séquence  :

[plantuml]
....

@startuml

actor Abonne
participant Bibliothèque
participant Livre

Abonne -> Bibliothèque: rendreLivre(livre: Livre)
Bibliothèque -> Livre: vérifierEmprunt(livre)
alt livre emprunte
    Livre -> Bibliothèque: marquerRetour(livre)
    Bibliothèque --> Abonné: confirmerRetour()
else livre non emprunté
    Bibliothèque --> Abonne: signalerErreur(livre)
end


@enduml
....

